#IBM DB2
/*
1. How many applications we receive from Lead Gen for SL in 2018-07.
*/
SELECT COUNT(*)
FROM GDSLINK.GDS_APPLICANT AS APP JOIN CRDTUSR.EXTRACT_KEY_MATCH AS EX ON (APP.APP_APPLICATION_ID = EX.APP_APPLICATION_ID)
WHERE APP.APP_SQ = 1 AND APP.APP_SOURCE IN ('LEADSMKT', 'DOT1818', 'DOT818', 'Dot818') AND CONCAT(CONCAT(YEAR(APP.APPLICATION_DATE), '-'), MONTH(APP.APPLICATION_DATE)) = '2018-8'
      AND EX.APP_PRODUCT_TYPE = 'SL'
      
 /*
 2. Following Q1, among those applications, what is the approval rate (num of approves / num of applications).
 */
 SELECT SUM(CASE WHEN AD.DEC_FINAL_DECISION = 'A' THEN 1 ELSE 0 END)/COUNT_BIG(*)
FROM GDSLINK.GDS_APPLICANT AS APP JOIN CRDTUSR.EXTRACT_KEY_MATCH AS EX ON (APP.APP_APPLICATION_ID = EX.APP_APPLICATION_ID)
                                  JOIN GDSLINK.GDS_APPLICATION AS APPL ON (APPL.APP_ID = APP.APP_ID)
                                  JOIN GDSLINK.GDS_APPLICATION_DECISION AS AD ON (AD.DEC_VERSION = APPL.DEC_VERSION AND AD.APP_ID = APPL.APP_ID)
WHERE APP.APP_SQ = 1 AND APP.APP_SOURCE IN ('LEADSMKT', 'DOT1818', 'DOT818', 'Dot818') AND CONCAT(CONCAT(YEAR(APP.APPLICATION_DATE), '-'), MONTH(APP.APPLICATION_DATE)) = '2018-8' AND EX.APP_PRODUCT_TYPE = 'SL'

/*
3. Following Q1, what is the average CF_score of all the applications, all the approves, all the declines.
*/
SELECT AVG(APP.CF_SCORE) AS SCORE_TOTAL,
AVG(CASE WHEN AD.DEC_FINAL_DECISION = 'A' THEN APP.CF_SCORE END) AS SCORE_APPROVED,
AVG(CASE WHEN AD.DEC_FINAL_DECISION = 'D' THEN APP.CF_SCORE END) AS SCORE_DECLINED
FROM GDSLINK.GDS_APPLICANT AS APP JOIN CRDTUSR.EXTRACT_KEY_MATCH AS EX ON (APP.APP_APPLICATION_ID = EX.APP_APPLICATION_ID)
                                  JOIN GDSLINK.GDS_APPLICATION AS APPL ON (APPL.APP_ID = APP.APP_ID)
                                  JOIN GDSLINK.GDS_APPLICATION_DECISION AS AD ON (AD.DEC_VERSION = APPL.DEC_VERSION AND AD.APP_ID = APPL.APP_ID)
WHERE APP.APP_SQ = 1 AND APP.APP_SOURCE IN ('LEADSMKT', 'DOT1818', 'DOT818', 'Dot818') AND CONCAT(CONCAT(YEAR(APP.APPLICATION_DATE), '-'), MONTH(APP.APPLICATION_DATE)) = '2018-8' AND EX.APP_PRODUCT_TYPE = 'SL'

/*
4. Following Q2, what is the average approval amount of the approved applications.
*/
SELECT AVG(AD.DEC_LOAN_AMOUNT1) AS AVG_LOAN_AMOUNT
FROM GDSLINK.GDS_APPLICANT AS APP JOIN CRDTUSR.EXTRACT_KEY_MATCH AS EX ON (APP.APP_APPLICATION_ID = EX.APP_APPLICATION_ID)
                                  JOIN GDSLINK.GDS_APPLICATION AS APPL ON (APPL.APP_ID = APP.APP_ID)
                                  JOIN GDSLINK.GDS_APPLICATION_DECISION AS AD ON (AD.DEC_VERSION = APPL.DEC_VERSION AND AD.APP_ID = APPL.APP_ID)
WHERE APP.APP_SQ = 1 AND APP.APP_SOURCE IN ('LEADSMKT', 'DOT1818', 'DOT818', 'Dot818') AND CONCAT(CONCAT(YEAR(APP.APPLICATION_DATE), '-'), MONTH(APP.APPLICATION_DATE)) = '2018-8' AND EX.APP_PRODUCT_TYPE = 'SL'
AND AD.DEC_FINAL_DECISION = 'A' 

/*
5. Following Q1, among those applications, how many have been converted to a loan.
*/
SELECT SUM(CASE WHEN AD1.DEC_LOAN_PAYMENT_AMT1 IS NOT NULL THEN 1 ELSE 0 END)/COUNT_BIG(*)
FROM GDSLINK.GDS_APPLICANT AS APP JOIN CRDTUSR.EXTRACT_KEY_MATCH AS EX ON (APP.APP_APPLICATION_ID = EX.APP_APPLICATION_ID)
                                  JOIN GDSLINK.GDS_APPLICATION AS APPL ON (APPL.APP_ID = APP.APP_ID)
                                  JOIN (SELECT AD.APP_ID, MAX(AD.DEC_VERSION), MAX(AD.DEC_LOAN_PAYMENT_AMT1) AS DEC_LOAN_PAYMENT_AMT1
                                        FROM GDSLINK.GDS_APPLICATION_DECISION AS AD
                                        GROUP BY AD.APP_ID) AS AD1 ON (AD1.APP_ID = APPL.APP_ID)
WHERE APP.APP_SQ = 1 AND APP.APP_SOURCE IN ('LEADSMKT', 'DOT1818', 'DOT818', 'Dot818') AND CONCAT(CONCAT(YEAR(APP.APPLICATION_DATE), '-'), MONTH(APP.APPLICATION_DATE)) = '2018-8'
AND EX.APP_PRODUCT_TYPE = 'SL'

/*
6. Following Q5, among those converted loans, how many are still active, how many are inactive.
*/
SELECT SUM (CASE WHEN AI.LOAN_STATUS = 'Active' THEN 1 ELSE 0 END) AS ACTIVE_COUNTS,
       SUM (CASE WHEN AI.LOAN_STATUS = 'Inactive' THEN 1 ELSE 0 END) AS INACTIVE_COUNTS
FROM GDSLINK.GDS_APPLICANT AS APP JOIN CRDTUSR.EXTRACT_KEY_MATCH AS EX ON (APP.APP_APPLICATION_ID = EX.APP_APPLICATION_ID)
                                  JOIN GDSLINK.GDS_APPLICATION AS APPL ON (APPL.APP_ID = APP.APP_ID)
                                  JOIN (SELECT DISTINCT AD.APP_ID
                                        FROM GDSLINK.GDS_APPLICATION_DECISION AS AD
                                        GROUP BY AD.APP_ID) AS AD1 ON (AD1.APP_ID = APPL.APP_ID)
                                  JOIN ODS.ACCOUNT_INFO AS AI ON (AI.ACCOUNT_ID = EX.ACCOUNT_ID)
WHERE APP.APP_SQ = 1 AND APP.APP_SOURCE = 'LEADSMKT' AND CONCAT(CONCAT(YEAR(AI.CREATE_DT), '-'), MONTH(AI.CREATE_DT)) = '2018-8'
